# Generated by Django 4.1.7 on 2023-03-28 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Pais',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('nacimiento', models.DateField()),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCrud.pais')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
